version: '3.8'
services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.12
    environment:
      ETCD_UNSUPPORTED_ARCH: arm64
    ports:
      - "2379:2379"
      - "2380:2380"
  redis:
    image: redis:alpine # 使用轻量级Redis镜像
    container_name: lw-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  mysql:
    image: mysql:alpine
    container_name: lw-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1qaz!QAZ
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  content-manage:
    build:
      context: ./content-manage
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - etcd
      - redis
      - mysql


  content-flow:
    build:
      context: ./content-flow
      dockerfile: Dockerfile-flow
    ports:
      - "7088:7088"
    depends_on:
      - etcd
      - redis
      - content-manage

  content-worker:
    build:
      context: .
      dockerfile: Dockerfile-worker
    ports:
      - "9090:9090"
    depends_on:
      - redis
      - etcd
      - content-manage

  content-system:
    build:
      context: ./content-system
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - etcd
      - redis
      - mysql



