# 使用官方 Go 作为基础镜像
FROM golang:1.23-alpine as builder

# 设置代理
ENV GOPROXY=https://goproxy.cn,direct

# 在alpine linux中：禁用CGO 不需要使用C代码
ENV CGO_ENABLED=0 GOOS=linux GOARCH=amd64


# 设置工作目录
WORKDIR /app

# copy go 依赖
COPY ./go.mod ./go.sum ./

# 下载 go 依赖
RUN go mod download

# copy 工程目录到工作目录
COPY ./ ./

# 编译
RUN go build -o /build/content-flow cmd/server/main.go

# 使用更小的基础镜像（如 alpine）
FROM alpine:latest

# 复制可执行文件
COPY --from=builder /build/content-flow /usr/local/bin/content-flow

# 暴露服务端口
EXPOSE 7088

# 配置文件挂载点
VOLUME /app/config
VOLUME /app/logs
# 启动应用
CMD ["/usr/local/bin/content-flow"]
