mysql:
  host: "localhost"
  port: 3306
  username: "root"
  password: "1qaz!QAZ"
  ChartSet: "utf8mb4"
  parseTime: "True"
  loc: "Local"
  MaxOpenConn: 4
  MaxIdleConn: 2

redis:
  host: "localhost"
  port: 6379
  username: ""
  password: ""
  DB: 0

redisWin:
  host: "localhost"
  port: 6379
  password: ""
  DB: 0


AppClient:
  host: "localhost"
  port: 9000

flowServiceClient:
  host: "localhost"
  port: 7088
  flowName: "content-flow"

EtcdClient:
  host: "localhost"
  port: 2379