mysql:
  host: "container-mysql"
  port: 3306
  username: "root"
  password: "3edc#EDC"
  ChartSet: "utf8mb4"
  parseTime: "True"
  loc: "Local"
  MaxOpenConn: 4
  MaxIdleConn: 2

redis:
  host: "container-redis"
  port: 6379
  username: ""
  password: ""
  DB: 0


flowServiceClient:
  host: "container-flow"
  port: 7088
  flowName: "content-flow"

EtcdClient:
  host: "container-etcd"
  port: 2379