name: 'default'
data-dir: '/var/lib/etcd/default.etcd'
listen-peer-urls: 'http://0.0.0.0:2380'
listen-client-urls: 'http://0.0.0.0:2379'
advertise-client-urls: 'http://172.18.0.3:2379'
initial-advertise-peer-urls: 'http://172.18.0.3:2380'
initial-cluster: 'default=http://172.18.0.3:2380'
initial-cluster-token: 'etcd-cluster-1'
initial-cluster-state: 'new'