server:
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:3edc#EDC@tcp(container-mysql)/?charset=utf8mb4&parseTime=True&loc=Local
  etcd:
    addr: container-etcd:2379
