server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1000s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1000s
data:
  database:
    driver: mysql
    source: root:1qaz!QAZ@tcp(127.0.0.1:3306)/?charset=utf8mb4&parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
