groups:
  - name: http_request_rules
    rules:
      - alert: HighHTTPErrorRate
        expr: rate(http_requests_total{code!="2xx"}[5m]) / rate(http_requests_total[5m]) > 0.05
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High HTTP error rate on {{ $labels.instance }}"
          description: "The HTTP error rate for {{ $labels.instance }} is above 5% over the last 5 minutes."